import { StyleSheet, type ViewStyle } from "react-native";
import { alpha, font, radius, size, space, type Theme } from "../theme";
import { useTheme } from "../themeContext";

// Per-theme style cache: module-level components (Button, IconButton) and
// BrowserApp share one built sheet per appearance.
const cache = new WeakMap<Theme, ReturnType<typeof buildAppStyles>>();
export const useStyles = (theme: Theme) => {
  let styles = cache.get(theme);
  if (!styles) {
    styles = buildAppStyles(theme);
    cache.set(theme, styles);
  }
  return styles;
};
export const useThemedStyles = () => useStyles(useTheme());

// All chrome styles, derived from tokens + the active theme. App.tsx calls
// this once per appearance change; every s.<key> in its JSX lives here.
const buildAppStyles = (t: Theme) => {
  // Settings rows and toggles render the identical sunken action-row shape.
  const settingsRow: ViewStyle = {
    minHeight: size.actionRow,
    paddingHorizontal: space.xxl,
    paddingVertical: space.lg,
    borderRadius: radius.field,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: t.sunken,
  };
  return StyleSheet.create({
    app: { flex: 1, backgroundColor: t.chrome },
    body: { flex: 1, flexDirection: "row" },
    // Floating chrome: the whole body sits on the chrome mat with a user
    // tunable frame padding (Settings → Layout), so the sidebar and the
    // content card read as two rounded surfaces instead of edge-to-edge.
    sidebar: {
      width: size.sidebar,
      backgroundColor: t.sidebar,
      borderRadius: radius.card,
      overflow: "hidden",
    },
    sidebarCollapsed: { width: size.rail },
    // Keep outgoing chrome until the enclosing width transition finishes.
    sidebarLayer: { ...StyleSheet.absoluteFill },
    sidebarLayerExpanded: {
      flexDirection: "column",
      paddingHorizontal: space.xxl,
      paddingTop: space.xxl,
      paddingBottom: space.xl,
    },
    sidebarLayerRail: {
      flexDirection: "column",
      paddingHorizontal: space.lg,
      paddingTop: space.xxl,
      paddingBottom: space.lg,
    },
    sidebarResizeHandle: {
      position: "absolute",
      top: 0,
      bottom: 0,
      right: 0,
      width: 10,
      alignItems: "center",
      justifyContent: "center",
    },
    sidebarTop: { gap: space.md },
    navigationRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: space.md,
    },
    navSpacer: { flex: 1 },
    identityRow: { flexDirection: "row", alignItems: "center", gap: space.lg },
    identityRowCollapsed: { justifyContent: "center" },
    hidden: { display: "none" },
    iconButton: {
      width: size.iconButton,
      height: size.iconButton,
      borderRadius: radius.control,
      alignItems: "center",
      justifyContent: "center",
    },
    icon: { color: t.icon, fontSize: font.icon, fontWeight: "600" },
    pressed: { opacity: alpha.pressed },
    disabled: { opacity: alpha.disabled },
    favoritesDropTarget: { minHeight: 12 },
    favoritesScroll: { flexGrow: 0, maxHeight: 132 },
    favorites: {
      flexDirection: "row",
      flexWrap: "wrap",
      gap: space.md,
      paddingVertical: space.xs,
    },
    favorite: {
      height: size.favorite,
      borderRadius: radius.control,
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: t.fieldOnChrome,
    },
    favoriteActive: {
      backgroundColor: t.pill,
      shadowColor: t.ringShadow,
      shadowOpacity: 0.13,
      shadowRadius: 3,
      shadowOffset: { width: 0, height: 1 },
      elevation: 1,
    },
    favoriteIcon: {
      width: 24,
      height: 24,
      alignItems: "center",
      justifyContent: "center",
    },
    favoriteInitial: {
      color: t.inkMuted,
      fontSize: font.body,
      fontWeight: "800",
    },
    separator: {
      height: 1,
      marginVertical: space.xl,
      backgroundColor: t.hairlineOnChrome,
    },
    tabScroll: { flex: 1 },
    // Break the tab list out of the sidebar's 12dp padding so rows get
    // Arc's 8dp pill inset (12 - 4).
    tabScrollWrap: { flex: 1, marginLeft: -4, marginRight: -4 },
    tabScrollContent: { paddingBottom: space.lg },
    workspaceCount: { color: t.inkMuted, fontSize: font.small },
    persistentSection: { minHeight: 48, paddingBottom: space.md },
    ordinarySection: { minHeight: 80 },
    spaceHeader: {
      minHeight: 28,
      paddingHorizontal: space.lg,
      gap: space.sm,
      flexDirection: "row",
      alignItems: "center",
      marginBottom: space.xs,
    },
    spaceHeaderTitle: {
      flex: 1,
      color: t.inkMuted,
      fontSize: font.small,
      fontWeight: "500",
    },
    rowPressed: { backgroundColor: t.fieldOnChrome },
    tabSelected: { backgroundColor: t.pill },
    tabClose: {
      width: 32,
      height: size.tabRow,
      justifyContent: "center",
      alignItems: "center",
      borderRadius: radius.control,
    },
    sectionRule: {
      height: StyleSheet.hairlineWidth,
      backgroundColor: t.hairlineOnChrome,
      marginVertical: space.md,
    },
    privateSection: { marginTop: space.md },
    privateHeader: {
      minHeight: 28,
      paddingLeft: space.xl,
      paddingRight: space.xs,
      gap: space.sm,
      flexDirection: "row",
      alignItems: "center",
      marginBottom: space.xs,
    },
    privateHeaderText: {
      flex: 1,
      color: t.inkMuted,
      fontSize: font.small,
      fontWeight: "500",
    },
    privateNewTab: {
      width: 32,
      height: 28,
      justifyContent: "center",
      alignItems: "center",
      borderRadius: radius.control,
    },
    privateBadge: {
      flexDirection: "row",
      alignItems: "center",
      gap: space.xs,
      paddingHorizontal: space.sm,
      height: 28,
      borderRadius: radius.control,
      backgroundColor: t.fieldOnChrome,
    },
    privateBadgeText: {
      color: t.accentStrong,
      fontSize: font.small,
      fontWeight: "600",
    },
    tab: {
      height: size.tabRow,
      paddingLeft: space.xl,
      paddingRight: space.xs,
      borderRadius: radius.control,
      overflow: "hidden",
      flexDirection: "row",
      alignItems: "center",
      gap: space.sm,
    },
    tabDrag: {
      flex: 1,
      height: size.tabRow,
      flexDirection: "row",
      alignItems: "center",
      gap: space.lg,
    },
    tabFavicon: {
      width: 16,
      height: 16,
      borderRadius: 4,
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: t.favChip,
    },
    tabFaviconText: { color: t.inkMuted, fontSize: font.micro },
    // Arc tab titles: 13px regular — quiet, readable.
    tabTitle: {
      flex: 1,
      color: t.ink,
      fontSize: font.input,
      fontWeight: "400",
    },
    newTab: {
      height: size.tabRow,
      paddingHorizontal: space.xl,
      borderRadius: radius.control,
      flexDirection: "row",
      alignItems: "center",
      gap: space.lg,
    },
    newTabText: { color: t.inkMuted, fontSize: font.bodyPlus },
    button: {
      paddingVertical: space.lg,
      paddingHorizontal: space.xl,
      borderRadius: radius.control,
      backgroundColor: t.sunken,
    },
    buttonText: { color: t.inkMuted, fontSize: font.body, fontWeight: "600" },
    sidebarBottom: {
      flexDirection: "row",
      alignItems: "center",
      gap: space.sm,
      paddingTop: space.lg,
    },
    sidebarBottomCollapsed: {
      flexDirection: "column",
      alignItems: "center",
      gap: space.xs,
    },
    spaceRailScroll: { flex: 1 },
    spaceRail: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      flexGrow: 1,
      gap: space.xs,
    },
    spaceChip: {
      width: 32,
      height: 34,
      borderRadius: radius.control,
      alignItems: "center",
      justifyContent: "center",
    },
    spaceChipActive: { backgroundColor: t.fieldOnChrome },
    spaceIndicator: {
      position: "absolute",
      bottom: 2,
      width: 3,
      height: 3,
      borderRadius: 2,
      backgroundColor: t.icon,
    },
    // Bookmark rows share tab selection bounds and the same icon/text columns.
    bookmarkTreeRow: {
      height: size.tabRow,
      paddingHorizontal: space.xl,
      borderRadius: radius.control,
      flexDirection: "row",
      alignItems: "center",
      gap: space.lg,
    },
    bookmarkTreeActive: { backgroundColor: t.pill },
    bookmarkTreeIndent: { paddingLeft: 30 },
    bookmarkDisclosure: {
      width: 10,
      color: t.inkFaint,
      fontSize: font.micro,
      fontWeight: "700",
    },
    profileInitial: { color: t.white, fontSize: font.body, fontWeight: "800" },
    chevron: { color: t.inkFaint, fontSize: font.icon },
    content: {
      flex: 1,
      marginLeft: space.sm,
      borderWidth: 1,
      borderColor: t.cardBorder,
      borderRadius: radius.card,
      overflow: "hidden",
      backgroundColor: t.surface,
      shadowColor: t.ringShadow,
      shadowOpacity: 0.14,
      shadowRadius: 14,
      shadowOffset: { width: 0, height: 4 },
      elevation: 4,
    },
    contentFullscreen: {
      marginLeft: 0,
      borderWidth: 0,
      borderRadius: 0,
      shadowOpacity: 0,
      elevation: 0,
    },
    paneFullscreen: { borderWidth: 0 },
    canvasToolbar: {
      height: size.toolbar,
      paddingHorizontal: space.xxl,
      flexDirection: "row",
      alignItems: "center",
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderBottomColor: t.hairline,
      backgroundColor: t.surfaceElevated,
    },
    compactNavigation: {
      flex: 1,
      flexDirection: "row",
      alignItems: "center",
      gap: space.md,
    },
    panes: { flex: 1, flexDirection: "row", backgroundColor: t.canvas },
    panesVertical: { flexDirection: "column" },
    pane: {
      flex: 1,
      // A zero-flex incoming pane must not seed Fabric's cached basis from its
      // header. Both panes share the available space from the first frame.
      flexBasis: 0,
      backgroundColor: t.white,
      borderWidth: 1,
      borderColor: "transparent",
      // Clip the incoming/outgoing content to its animated pane bounds.
      overflow: "hidden",
    },
    paneFocused: { borderColor: t.paneFocus },
    paneHeader: {
      height: size.row,
      paddingHorizontal: space.xl,
      flexDirection: "row",
      alignItems: "center",
      gap: space.lg,
      backgroundColor: t.sunken,
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderBottomColor: t.hairline,
    },
    paneHeaderFocused: { backgroundColor: t.sunkenStrong },
    paneHeaderTitle: {
      flex: 1,
      color: t.inkMuted,
      fontSize: font.small,
      fontWeight: "600",
    },
    paneDragHint: { color: t.inkFaint, fontSize: font.bodyPlus },
    divider: {
      width: 10,
      marginHorizontal: -4,
      zIndex: 3,
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: "transparent",
    },
    dividerVertical: {
      width: "100%",
      height: 10,
      marginHorizontal: 0,
      marginVertical: -4,
    },
    dividerHandle: {
      width: 2,
      height: size.row,
      borderRadius: 2,
      backgroundColor: t.accent,
    },
    dividerHandleVertical: { width: size.row, height: 2 },
    dropPreview: {
      position: "absolute",
      zIndex: 8,
      borderWidth: 2,
      borderColor: t.dropBorder,
      borderRadius: radius.tile,
      backgroundColor: t.dropFill,
    },
    dropLeft: { left: space.lg, top: space.lg, bottom: space.lg, width: "48%" },
    dropRight: {
      right: space.lg,
      top: space.lg,
      bottom: space.lg,
      width: "48%",
    },
    dropTop: { left: space.lg, right: space.lg, top: space.lg, height: "47%" },
    dropBottom: {
      left: space.lg,
      right: space.lg,
      bottom: space.lg,
      height: "47%",
    },
    dragGhost: {
      position: "absolute",
      zIndex: 50,
      width: 144,
      height: 36,
      paddingHorizontal: space.xxl,
      justifyContent: "center",
      borderRadius: radius.field,
      backgroundColor: t.ghost,
      shadowColor: t.ringShadow,
      shadowOpacity: 0.2,
      shadowRadius: 10,
      shadowOffset: { width: 0, height: 4 },
      elevation: 10,
    },
    dragGhostText: {
      color: t.inkMuted,
      fontSize: font.small,
      fontWeight: "700",
    },
    surface: { flex: 1 },
    paneContent: { flex: 1 },
    newTabOverlay: {
      ...StyleSheet.absoluteFill,
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: t.surface,
    },
    newTabPanel: {
      width: "70%",
      maxWidth: 440,
      alignItems: "center",
      gap: space.xxxl,
    },
    newTabHeading: {
      alignSelf: "flex-start",
      color: t.inkFaint,
      fontSize: font.small,
      fontWeight: "700",
      letterSpacing: 0.8,
    },
    newTabGrid: { flexDirection: "row", flexWrap: "wrap", gap: space.xxxl },
    newTabTile: { width: 80, alignItems: "center", gap: space.md },
    newTabTileIcon: {
      width: 46,
      height: 46,
      borderRadius: radius.tile,
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: t.white,
      shadowColor: t.ringShadow,
      shadowOpacity: 0.08,
      shadowRadius: 6,
      shadowOffset: { width: 0, height: 2 },
      elevation: 2,
    },
    newTabTileLabel: {
      color: t.inkMuted,
      fontSize: font.small,
      fontWeight: "600",
    },
    newTabHint: { color: t.inkFaint, fontSize: font.body, textAlign: "center" },
    quickOpenDialog: { width: "90%", maxWidth: 560, gap: space.xl },
    quickOpenRow: {
      flexDirection: "row",
      gap: space.xl,
      paddingVertical: space.xs,
    },
    quickOpenTile: { width: 86, alignItems: "center", gap: space.sm },
    quickOpenTileIcon: {
      width: 36,
      height: 36,
      borderRadius: radius.field,
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: t.white,
      shadowColor: t.ringShadow,
      shadowOpacity: 0.08,
      shadowRadius: 5,
      shadowOffset: { width: 0, height: 2 },
      elevation: 2,
    },
    quickOpenTileLabel: {
      color: t.inkMuted,
      fontSize: font.small,
      fontWeight: "600",
    },
    quickOpenHint: { color: t.inkFaint, fontSize: font.body },
    railContent: {
      alignItems: "center",
      gap: space.lg,
      paddingBottom: space.lg,
    },
    railHeader: { alignItems: "center", gap: space.lg },
    railItem: {
      width: size.railItem,
      height: size.railItem,
      borderRadius: radius.control,
      alignItems: "center",
      justifyContent: "center",
    },
    railIcon: {
      width: 26,
      height: 26,
      borderRadius: radius.control,
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: t.railIconTile,
    },
    railInitial: { color: t.inkMuted, fontSize: font.small, fontWeight: "800" },
    railTabActive: { backgroundColor: t.pill },
    railSeparator: {
      width: 16,
      height: 1,
      marginVertical: space.md,
      backgroundColor: t.hairlineOnChrome,
    },
    minis: {
      position: "absolute",
      right: space.xxxl,
      bottom: space.xxxl,
      gap: space.lg,
    },
    mini: {
      width: 310,
      height: 208,
      backgroundColor: t.white,
      borderRadius: radius.tile,
      overflow: "hidden",
      borderWidth: 1,
      borderColor: t.cardBorder,
      shadowColor: t.ringShadow,
      shadowOpacity: 0.22,
      shadowRadius: 16,
      shadowOffset: { width: 0, height: 6 },
      elevation: 7,
    },
    miniHeader: {
      height: 36,
      paddingLeft: space.xxl,
      paddingRight: space.sm,
      flexDirection: "row",
      alignItems: "center",
      backgroundColor: t.white,
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderBottomColor: t.hairline,
    },
    miniTitle: {
      flex: 1,
      color: t.inkMuted,
      fontSize: font.small,
      fontWeight: "600",
    },
    overlay: {
      position: "absolute",
      top: 0,
      left: 0,
      right: 0,
      bottom: 0,
      backgroundColor: t.scrim,
      justifyContent: "center",
      alignItems: "center",
    },
    overlayTouch: {
      ...StyleSheet.absoluteFill,
      justifyContent: "center",
      alignItems: "center",
    },
    // Swallows taps on the card itself so the outside-tap closer behind it
    // only fires for taps on the surrounding sheet area.
    sheetUnderlay: { ...StyleSheet.absoluteFill },
    dialog: {
      width: "90%",
      maxWidth: 620,
      maxHeight: "78%",
      padding: space.xxxl,
      backgroundColor: t.surfaceElevated,
      borderRadius: radius.dialog,
      gap: space.lg,
      shadowColor: t.ringShadow,
      shadowOpacity: 0.24,
      shadowRadius: 24,
      shadowOffset: { width: 0, height: 10 },
      elevation: 10,
    },
    dialogTitle: { color: t.ink, fontSize: font.title, fontWeight: "700" },
    dialogHelp: {
      color: t.inkFaint,
      fontSize: font.body,
      lineHeight: space.xxxl,
    },
    // The settings body scrolls inside the fixed-height dialog card; without
    // it the rows paint past the card's rounded bottom.
    dialogScroll: { flexGrow: 0, overflow: "hidden" },
    settingsDialog: { width: "90%", maxWidth: 480 },
    bookmarkDialog: { width: "90%", maxWidth: 560, maxHeight: "84%" },
    bookmarkForm: { gap: space.lg },
    bookmarkActions: { flexDirection: "row", gap: space.md },
    bookmarkList: { maxHeight: 230 },
    bookmarkRow: {
      minHeight: size.bookmarkRow,
      flexDirection: "row",
      alignItems: "center",
      paddingLeft: space.xl,
      paddingRight: space.sm,
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderBottomColor: t.hairline,
    },
    bookmarkCopy: { flex: 1, marginRight: space.sm },
    folderRow: {
      flex: 1,
      flexDirection: "row",
      alignItems: "center",
      gap: space.lg,
    },
    folderIcon: { fontSize: font.icon },
    dialogHeader: { flexDirection: "row", alignItems: "flex-start" },
    dialogHeadingCopy: { flex: 1 },
    settingsSection: {
      marginTop: space.xl,
      color: t.inkFaint,
      fontSize: font.micro,
      fontWeight: "800",
      letterSpacing: 0.9,
    },
    optionRow: { flexDirection: "row", gap: space.lg },
    appearanceOption: {
      flex: 1,
      padding: space.lg,
      borderWidth: 1,
      borderColor: t.hairline,
      borderRadius: radius.tile,
      gap: space.lg,
    },
    appearanceOptionSelected: {
      borderColor: t.accentStrong,
      backgroundColor: t.sunken,
    },
    appearanceSwatch: {
      height: 36,
      borderRadius: radius.control,
      borderWidth: 5,
      borderColor: t.surfaceElevated,
    },
    optionTitle: { color: t.ink, fontSize: font.body, fontWeight: "700" },
    optionDescription: {
      color: t.inkFaint,
      fontSize: font.micro,
      marginTop: space.xs,
    },
    settingsAction: settingsRow,
    settingsToggle: settingsRow,
    settingsToggleCopy: { flex: 1, marginRight: space.xxl },
    stepperRow: { flexDirection: "row", alignItems: "center", gap: space.md },
    stepperValue: {
      color: t.ink,
      fontSize: font.bodyPlus,
      fontWeight: "700",
      minWidth: 44,
      textAlign: "center",
    },
    commandInput: {
      height: size.input,
      paddingHorizontal: space.xxl,
      borderRadius: radius.field,
      color: t.ink,
      backgroundColor: t.sunken,
      fontSize: font.input,
    },
    keymapInput: {
      height: 170,
      padding: space.xxl,
      borderRadius: radius.field,
      color: t.ink,
      backgroundColor: t.sunken,
      fontSize: font.body,
      textAlignVertical: "top",
    },
    error: { padding: space.lg, color: t.errorInk, backgroundColor: t.errorBg },
    noticeBanner: {
      position: "absolute",
      top: space.xxxl,
      alignSelf: "center",
      zIndex: 60,
      paddingHorizontal: space.xxl,
      paddingVertical: space.lg,
      borderRadius: radius.tile,
      backgroundColor: t.noticeBg,
    },
    noticeText: { color: t.noticeInk, fontSize: font.body, fontWeight: "600" },
  });
};
