// Static chrome roles compile through Uniwind. ScopedVariables supplies each
// root/Space palette; geometry and Animated values stay at their native hosts.
export const appClasses = {
  app: "flex-1 bg-chrome",
  body: "flex-1 flex-row",
  sidebar: "w-sidebar bg-sidebar rounded-card overflow-hidden",
  sidebarCollapsed: "w-rail",
  sidebarLayer: "absolute inset-0",
  sidebarLayerExpanded: "flex-col px-xxl pt-xxl pb-xl",
  sidebarLayerRail: "flex-col px-sm pt-xxl pb-lg",
  sidebarResizeHandle:
    "absolute top-0 bottom-0 right-0 w-[12px] items-center justify-center",
  sidebarResizeGrip: "w-[3px] h-[32px] rounded-[2px] bg-ink-muted",
  sidebarTop: "gap-md",
  navigationRow: "flex-row items-center gap-md",
  navSpacer: "flex-1",
  identityRow: "flex-row items-center gap-lg",
  identityRowCollapsed: "justify-center",
  hidden: "hidden",
  iconButton:
    "w-icon-button h-icon-button rounded-control items-center justify-center",
  icon: "text-icon text-icon-size font-semibold",
  pressed: "opacity-pressed",
  disabled: "opacity-disabled",
  favoritesDropTarget: "min-h-[12px]",
  favoritesScroll: "grow-0 max-h-[132px]",
  favorites: "flex-row flex-wrap gap-md py-xs",
  favorite:
    "h-favorite rounded-control items-center justify-center bg-field-on-chrome",
  favoriteActive: "bg-pill shadow-favorite-active",
  favoriteIcon: "w-[24px] h-[24px] items-center justify-center",
  favoriteInitial: "text-ink-muted text-body font-extrabold",
  separator: "h-[1px] my-xl bg-hairline-on-chrome",
  tabScroll: "flex-1",
  tabScrollWrap: "flex-1 -ml-sm -mr-sm",
  tabScrollContent: "pb-lg",
  workspaceCount: "text-ink-muted text-small",
  persistentSection: "min-h-[48px] pb-md",
  ordinarySection: "min-h-[44px]",
  spaceHeader: "min-h-[28px] px-lg gap-sm flex-row items-center mb-xs",
  spaceHeaderTitle: "flex-1 text-ink-muted text-small font-medium",
  rowPressed: "bg-field-on-chrome",
  tabSelected: "bg-pill",
  tabClose: "w-[32px] h-tab-row justify-center items-center rounded-control",
  sectionRule: "h-hairline bg-hairline-on-chrome my-md",
  privateSection: "mt-md",
  privateHeader: "min-h-[28px] pl-xl pr-xs gap-sm flex-row items-center mb-xs",
  privateHeaderText: "flex-1 text-ink-muted text-small font-medium",
  privateNewTab:
    "w-[32px] h-[28px] justify-center items-center rounded-control",
  privateBadge:
    "flex-row items-center gap-xs px-sm h-[28px] rounded-control bg-field-on-chrome",
  privateBadgeText: "text-ink text-small font-semibold",
  tab: "h-tab-row pl-xl pr-xs rounded-control overflow-hidden flex-row items-center gap-sm",
  tabDrag: "flex-1 h-tab-row flex-row items-center gap-lg",
  tabFavicon:
    "w-[16px] h-[16px] rounded-[4px] items-center justify-center bg-fav-chip",
  tabFaviconText: "text-ink-muted text-micro",
  tabTitle: "flex-1 text-ink text-input font-normal",
  newTab: "h-tab-row px-xl rounded-control flex-row items-center gap-lg",
  newTabText: "text-ink-muted text-body-plus",
  button: "py-lg px-xl rounded-control bg-sunken",
  buttonText: "text-ink-muted text-body font-semibold",
  sidebarBottom: "flex-row items-center gap-sm pt-lg",
  sidebarBottomCollapsed: "flex-col items-center gap-xs",
  spaceRailScroll: "flex-1",
  spaceRail: "flex-row items-center justify-center grow gap-xs",
  spaceChip: "w-[32px] h-[34px] rounded-control items-center justify-center",
  spaceChipActive: "bg-field-on-chrome",
  spaceIndicator: "absolute bottom-xs w-[3px] h-[3px] rounded-[2px] bg-icon",
  bookmarkTreeRow:
    "h-tab-row px-xl rounded-control flex-row items-center gap-lg",
  bookmarkTreeActive: "bg-pill",
  bookmarkTreeIndent: "pl-xl",
  folderChildren: "ml-[20px] border-l border-l-hairline-on-chrome mb-[3px]",
  emptyFolder: "px-xxl py-md text-ink-muted text-body",
  bookmarkDisclosure: "w-[10px] text-ink-faint text-micro font-bold",
  profileInitial: "text-white text-body font-extrabold",
  chevron: "text-ink-faint text-icon-size",
  content:
    "flex-1 ml-sm border border-card-border rounded-card overflow-hidden bg-surface shadow-content",
  contentFullscreen: "ml-0 border-0 rounded-none shadow-content-fullscreen",
  paneFullscreen: "border-0",
  canvasToolbar:
    "h-toolbar px-xxl flex-row items-center border-b-hairline-width border-b-hairline bg-surface-elevated",
  compactNavigation: "flex-1 flex-row items-center gap-md",
  panes: "flex-1 flex-row bg-canvas",
  panesVertical: "flex-col",
  pane: "flex-1 basis-0 bg-white border border-transparent overflow-hidden",
  paneFocused: "border-pane-focus",
  paneHeader:
    "h-row px-xl flex-row items-center gap-lg bg-sunken border-b-hairline-width border-b-hairline",
  paneHeaderFocused: "bg-sunken-strong",
  paneHeaderTitle: "flex-1 text-ink-muted text-small font-semibold",
  paneDragHint: "text-ink-faint text-body-plus",
  divider: "w-[10px] -mx-sm z-[3] items-center justify-center bg-transparent",
  dividerVertical: "w-full h-[10px] mx-0 -my-sm",
  dividerHandle: "w-[2px] h-row rounded-[2px] bg-accent",
  dividerHandleVertical: "w-row h-[2px]",
  dropPreview:
    "absolute z-[8] border-[2px] border-drop-border rounded-tile bg-drop-fill",
  dropLeft: "left-lg top-lg bottom-lg w-[48%]",
  dropRight: "right-lg top-lg bottom-lg w-[48%]",
  dropTop: "left-lg right-lg top-lg h-[47%]",
  dropBottom: "left-lg right-lg bottom-lg h-[47%]",
  dragGhost:
    "absolute z-[50] w-[144px] h-[36px] px-xxl justify-center rounded-field bg-ghost shadow-drag-ghost",
  dragGhostText: "text-ink-muted text-small font-bold",
  surface: "flex-1",
  paneContent: "flex-1",
  findOverlay: "absolute inset-0 z-[30]",
  newTabOverlay: "absolute inset-0 items-center justify-center bg-surface",
  newTabPanel: "w-[70%] max-w-[440px] items-center gap-xxxl",
  newTabHeading:
    "self-start text-ink-faint text-small font-bold tracking-[0.8px]",
  newTabGrid: "flex-row flex-wrap gap-xxxl",
  newTabTile: "w-[80px] items-center gap-md",
  newTabTileIcon:
    "w-[46px] h-[46px] rounded-tile items-center justify-center bg-white shadow-new-tab-tile-icon",
  newTabTileLabel: "text-ink-muted text-small font-semibold",
  newTabHint: "text-ink-faint text-body text-center",
  quickOpenDialog: "w-[90%] max-w-[560px] gap-xl",
  quickOpenRow: "flex-row gap-xl py-xs",
  quickOpenTile: "w-[86px] items-center gap-sm",
  quickOpenTileIcon:
    "w-[36px] h-[36px] rounded-field items-center justify-center bg-white shadow-quick-open-tile-icon",
  quickOpenTileLabel: "text-ink-muted text-small font-semibold",
  quickOpenHint: "text-ink-faint text-body",
  railContent: "items-center gap-xs pb-lg",
  railHeader: "items-center gap-xs",
  railItem: "w-[44px] h-[44px] rounded-control items-center justify-center",
  railIcon:
    "w-[26px] h-[26px] rounded-control items-center justify-center bg-rail-icon-tile",
  railInitial: "text-ink-muted text-small font-extrabold",
  railTabActive: "bg-pill",
  railSeparator: "w-[16px] h-[1px] my-md bg-hairline-on-chrome",
  minis: "absolute right-xxxl bottom-xxxl gap-lg",
  mini: "w-[310px] h-[208px] bg-white rounded-tile overflow-hidden border border-card-border shadow-mini",
  miniHeader:
    "h-[36px] pl-xxl pr-sm flex-row items-center bg-white border-b-hairline-width border-b-hairline",
  miniTitle: "flex-1 text-ink-muted text-small font-semibold",
  overlay:
    "absolute top-0 left-0 right-0 bottom-0 bg-scrim justify-center items-center",
  overlayTouch: "absolute inset-0 justify-center items-center",
  sheetUnderlay: "absolute inset-0",
  dialog:
    "w-[90%] max-w-[620px] max-h-[78%] p-xxxl bg-surface-elevated rounded-dialog gap-lg shadow-dialog",
  dialogTitle: "text-ink text-title font-bold",
  dialogHelp: "text-ink-muted text-body leading-xxxl",
  dialogScroll: "grow-0 overflow-hidden",
  settingsDialog: "w-[90%] max-w-[480px]",
  bookmarkDialog: "w-[90%] max-w-[560px] max-h-[84%]",
  bookmarkForm: "gap-lg",
  bookmarkActions: "flex-row gap-md",
  bookmarkList: "max-h-[230px]",
  bookmarkRow:
    "min-h-bookmark-row flex-row items-center pl-xl pr-sm border-b-hairline-width border-b-hairline",
  bookmarkCopy: "flex-1 mr-sm",
  folderRow: "flex-1 flex-row items-center gap-lg",
  folderIcon: "text-icon-size",
  dialogHeader: "flex-row items-start",
  dialogHeadingCopy: "flex-1",
  settingsSection: "mt-[20px] mb-lg text-ink text-[15px] font-semibold",
  optionRow: "flex-row gap-lg",
  appearanceOption: "flex-1 p-lg border border-hairline rounded-tile gap-lg",
  appearanceOptionSelected: "border-accent-strong bg-sunken",
  appearanceSwatch:
    "h-[36px] rounded-control border-[5px] border-surface-elevated",
  optionTitle: "text-ink text-[15px] leading-[22px] font-semibold",
  optionDescription: "text-ink-muted text-input-plus leading-[20px] mt-xs",
  settingsAction:
    "min-h-action-row px-sm py-xxl border-b-hairline-width border-b-hairline flex-row items-center justify-between flex-wrap gap-lg mb-sm",
  settingsToggle:
    "min-h-action-row px-sm py-xxl border-b-hairline-width border-b-hairline flex-row items-center justify-between flex-wrap gap-lg mb-sm",
  settingsToggleCopy: "flex-1 min-w-[120px] mr-xxl",
  consentPage: "gap-[20px]",
  consentChoices: "flex-row flex-wrap gap-lg mt-xxl",
  consentChoice:
    "min-h-[48px] max-w-full p-xxl flex-row items-center gap-lg border border-hairline rounded-control",
  consentChoiceSelected: "border-ink bg-sunken-strong",
  consentIntro: "flex-row items-start gap-xxl p-xxxl rounded-card bg-sunken",
  consentCopy: "flex-1 min-w-[120px]",
  consentGroup:
    "mt-xxl border-hairline-width border-hairline rounded-card overflow-hidden",
  consentRow:
    "min-h-[56px] flex-row flex-wrap items-center gap-xxl py-[14px] px-xxl border-b-hairline-width border-b-hairline",
  consentButton:
    "min-h-[48px] px-xxxl py-xl max-w-full justify-center rounded-control bg-sunken-strong",
  consentStatus: "text-ink-muted text-input leading-[20px] mt-md font-semibold",
  consentOrigin:
    "text-ink text-input-plus leading-[21px] font-semibold bg-sunken p-[14px]",
  consentDetails: "px-xxl gap-xxl",
  consentNotice:
    "text-ink bg-sunken p-xxl rounded-control text-input-plus leading-[21px]",
  consentError:
    "text-error-ink bg-error-bg p-xxl rounded-control text-input-plus leading-[21px]",
  stepperRow: "flex-row items-center gap-md",
  stepperValue: "text-ink text-body-plus font-bold min-w-[44px] text-center",
  commandInput: "h-input px-xxl rounded-field text-ink bg-sunken text-input",
  keymapInput:
    "h-[170px] p-xxl rounded-field text-ink bg-sunken text-body [text-align-vertical:top]",
  error: "p-lg text-error-ink bg-error-bg",
  noticeBanner:
    "absolute top-xxxl self-center z-[60] px-xxl py-lg rounded-tile bg-notice-bg",
  noticeText: "text-notice-ink text-body font-semibold",
} as const;
